 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });

//Going to silence this part. Only returning the API at /
/*app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })
*/


// If you go directly to the base URL, we will return the header info:
//ipaddress = Client's Public IP
//language = Client's browser's first accepted language
//software = Client's OS - based on CLient's browser's description
app.route('/')
    .get(function(req, res) {
    var ipString = req.header("X-Forwarded-For").split(',');  
    var langString = req.headers["accept-language"].split(','); 
    var osString = req.headers["user-agent"];
    osString = osString.substring(osString.indexOf('(')+1, osString.indexOf(')'));
    //osString = typeof(osString);
    var results = 
        {
          "ipaddress": ipString[0],
          "language": langString[0],
          "software": osString
        };
      
      res.end(JSON.stringify(results));
    })

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

